runtime: python27
# env: flex
api_version: 1
threadsafe: yes
service: bot
# entrypoint: gunicorn -b :$PORT bot.bot_gae:app

handlers:
- url: .*
  script: bot.app.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: ssl
  version: latest
- name: MySQLdb
  version: "1.2.5"

instance_class: F1
automatic_scaling:
  min_idle_instances: 2
  max_pending_latency: 1s

env_variables:
  ENV: prod
