"""empty message

Revision ID: 19dfa4d7e92b
Revises: 75f0eb77c544
Create Date: 2018-03-20 15:10:29.329976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19dfa4d7e92b'
down_revision = '75f0eb77c544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_flow', 'flows', ['chat_id', 'flow_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_flow', 'flows', type_='unique')
    # ### end Alembic commands ###
