"""empty message

Revision ID: 75f0eb77c544
Revises: aab91dc3fe57
Create Date: 2018-03-20 13:34:45.444538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f0eb77c544'
down_revision = 'aab91dc3fe57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('flow_name', sa.String(length=155), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flows_chat_id'), 'flows', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flows_chat_id'), table_name='flows')
    op.drop_table('flows')
    # ### end Alembic commands ###
