"""empty message

Revision ID: aab91dc3fe57
Revises: 1f74c907cc12
Create Date: 2018-03-20 13:03:46.878603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab91dc3fe57'
down_revision = '1f74c907cc12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.add_column('restaurants', sa.Column('fdde_id', sa.Integer(), nullable=True))
    op.add_column('restaurants', sa.Column('lh_id', sa.Integer(), nullable=True))
    op.add_column('restaurants', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('restaurants', sa.Column('pde_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_restaurants_chat_id'), 'restaurants', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurants_chat_id'), table_name='restaurants')
    op.drop_column('restaurants', 'pde_id')
    op.drop_column('restaurants', 'name')
    op.drop_column('restaurants', 'lh_id')
    op.drop_column('restaurants', 'fdde_id')
    op.drop_column('restaurants', 'chat_id')
    # ### end Alembic commands ###
