"""empty message

Revision ID: b3655528675f
Revises: 19dfa4d7e92b
Create Date: 2018-03-20 18:00:58.494987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3655528675f'
down_revision = '19dfa4d7e92b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flows', sa.Column('restaurant_id', sa.String(length=36), nullable=True))
    op.add_column('restaurants', sa.Column('fdde', sa.String(length=36), nullable=True))
    op.add_column('restaurants', sa.Column('lhde', sa.String(length=36), nullable=True))
    op.add_column('restaurants', sa.Column('pde', sa.String(length=36), nullable=True))
    op.drop_column('restaurants', 'lh_id')
    op.drop_column('restaurants', 'pde_id')
    op.drop_column('restaurants', 'fdde_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('fdde_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('pde_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('lh_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('restaurants', 'pde')
    op.drop_column('restaurants', 'lhde')
    op.drop_column('restaurants', 'fdde')
    op.drop_column('flows', 'restaurant_id')
    # ### end Alembic commands ###
